os:
    - linux
    - osx

install:
    - cd ${TRAVIS_BUILD_DIR}
    - ./travis-get-deps.sh
    - pip install --user codecov

language: cpp
compiler:
    - gcc
    - clang

script:
    - cd ${TRAVIS_BUILD_DIR}
    - make all test-rss
    - cd test && ./test-rss

after_success:
    - cd ${TRAVIS_BUILD_DIR}
    - make distclean
    - make PROFILE=1 all test-rss
    - cd test && ./test-rss
    - codecov --gcov-glob '*/test/*'
